services:
  api:
    image: ghcr.io/breaktness/aukaniapp-backend:latest
    container_name: aukani_api
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./downloads:/app/downloads

volumes: {}
